### ISSUE TITLE
Scinan v2 api

### ISSUE THREAD

**Issue by SkogDev** [PetterRuud/com.scinan.api#18]
Looks like scinan v1 api for thermostats is having some issues. Had to capture the packets from the latest android-app to figure out why things stopped working. They have updated to v2, but a new user account is required. Smart-e IOS app is not updated as of now. Hope you have the time to do an update.

**Comment by PetterRuud** [comment]
I dont have a scinan device anymore, so cant test it.

**Comment by late4marshmellow** [comment]
hi @SkogDev you can try my rework of PetterRuuds app
https://github.com/late4marshmellow/com.l4m.saswell_scinan
i am now looking into getting it published, since this works for several devices i recommend only using the saswell or scinan devices so you wont need to readd them if i later decide to remove the model specific drivers.

**Comment by SkogDev** [comment]
@late4marshmellow Thanks a lot!
I wrote my own implementation in april, so I really don't need it. But mine is not published, so if you could get yours out to the people, that would be great!
